dist: trusty
language: node_js
node_js:
  - "4.4"
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_script:
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls.js
